apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    lb-service: movie-service
  name: movie-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      lb-service: movie-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        lb-service: movie-service
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: movie-service
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: movie-service
          args:
            - uvicorn
            - app.main:app
            - --reload
            - --host
            - 0.0.0.0
            - --port
            - "8000"
          env:
            - name: CAST_SERVICE_HOST_URL
              value: http://cast_service:8000/api/v1/casts/
            - name: DATABASE_URI
              value: postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev
      restartPolicy: Always
      volumes:
        - name: movie-service