apiVersion: v1
kind: Service
metadata:
  labels:
    lb-service: movie-service
  name: movie-service
spec:
  ports:
    - name: movie-service-port
      port: {{ .Values.service.hostPort }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    lb-service: movie-service