apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    lb-service: cast-service
  name: cast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      lb-service: cast-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        lb-service: cast-service
    spec:
      containers:
        - args:
            - uvicorn
            - app.main:app
            - --reload
            - --host
            - 0.0.0.0
            - --port
            - "8000"
          env:
            - name: DATABASE_URI
              value: postgresql://cast_db_username:cast_db_password@cast_db/cast_db_dev
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: cast-service
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: cast-service
      restartPolicy: Always
      volumes:
        - name: cast-service
