apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "movie_db.fullname" . }}
  labels:
    lb-service: postgres-movie-db
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    lb-service: postgres-movie-db
  name: postgres-movie-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi