apiVersion: v1
kind: Service
metadata:
  name: movie-db
  labels:
    lb-service: movie-db
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    lb-service: movie-db
