apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    lb-service: movie-db
  name: movie-db
spec:
  replicas: 1
  selector:
    matchLabels:
      lb-service: movie-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        lb-service: movie-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: movie_db_dev
            - name: POSTGRES_PASSWORD
              value: movie_db_password
            - name: POSTGRES_USER
              value: movie_db_username
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: movie-db
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      restartPolicy: Always
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
