apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    lb-service: movie-db
  name: movie-db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      lb-service: movie-db
  serviceName: movie-db
  template:
    metadata:
      labels:
        lb-service: movie-db
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: movie-db
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: movie-db-configmap
          - secretRef:
              name: movie-db-secret
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
