apiVersion: v1
kind: Service
metadata:
  name: cast-db
  labels:
    lb-service: cast-db
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cast_db.selectorLabels" . | nindent 4 }}
