apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    lb-service: cast-db
  name: cast-db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      lb-service: cast-db
  serviceName: cast-db
  template:
    metadata:
      labels:
        lb-service: cast-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: cast_db_dev
            - name: POSTGRES_PASSWORD
              value: cast_db_password
            - name: POSTGRES_USER
              value: cast_db_username
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: cast-db
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data-cast
      volumes:
        - name: postgres-data-cast
          persistentVolumeClaim:
            claimName: postgres-data-cast
