apiVersion: v1
kind: Service
metadata:
  labels:
    lb-service: nginx
  name: nginx
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: nginx-port
      port: 8081
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}
  selector:
    lb-service: nginx
